# --- WEB CONFIG ---
server.port=443

# --- SSL CONFIG ---
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${SSL_KEY_STORE_PATH}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}

# --- DATABASE CONFIG ---
spring.jpa.hibernate.ddl-auto=update
hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/${BASENAME}?serverTimezone=Europe/Moscow&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${USERDBNAME}
spring.datasource.password=${USERDBPASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.data.jdbc.dialect=mysql


# --- APP SPECIFIC ---
app.share.folder.path=${SALARY_FOLDER_PATH}

# --- I18N ---
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

# --- LOGGING ---
logging.level.og.portal.zarplata.filter.RemoteIpResolverFilter=INFO
logging.level.og.portal.zarplata.controller.HelloController=INFO
logging.level.waffle=TRACE
logging.level.org.springframework.security=DEBUG

# --- WAFFLE (SSO) ---
waffle.sso.enabled=true
waffle.sso.protocols=NTLM
waffle.sso.basic-enabled=false

spring.thymeleaf.cache=false
