name: Deploy runner
on:
  push:
    branches: ["master"]
jobs:
  prepare-environment:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Clean and compile
        run: mvn clean compile
      - name: Deploy
        run: mvn tomcat7:deploy